blank_issues_enabled: false
contact_links:
  - name: "ğŸ“Œ ê¸°ëŠ¥ ì¶”ê°€ PR"
    url: "https://github.com/coffee-curation/compare/{branch}...{branch}?expand=1&template=feature.md"
    about: "ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ì¶”ê°€í•  ë•Œ ì‚¬ìš©í•˜ëŠ” PR í…œí”Œë¦¿ì…ë‹ˆë‹¤."
  - name: "ğŸ ë²„ê·¸ ìˆ˜ì • PR"
    url: "https://github.com/coffee-curation/compare/{branch}...{branch}?expand=1&template=bug_fix.md"
    about: "ë²„ê·¸ë¥¼ ìˆ˜ì •í•  ë•Œ ì‚¬ìš©í•˜ëŠ” PR í…œí”Œë¦¿ì…ë‹ˆë‹¤."
