blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ & ê¸°íƒ€ ìš”ì²­
    url: https://github.com/coffee-curation/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ ë…¼ì˜ëŠ” Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”.
